### ISSUE TITLE
composer install fails on cakephp application template

### ISSUE THREAD

**Issue by quasiperfect** [gourmet/social-meta#2]
composer require gourmet/social-meta:~1.0
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for gourmet/social-meta ~1.0 -> satisfiable by gourme
t/social-meta[v1.0.0].
    - gourmet/social-meta v1.0.0 requires cakephp/cakephp 3.0.*-dev -> no matchi
ng package found.

Potential causes:
- A typo in the package name
- The package is not available in a stable-enough version according to your min
  imum-stability setting
  see https://getcomposer.org/doc/04-schema.md#minimum-stability for more det
  ails.

Read https://getcomposer.org/doc/articles/troubleshooting.md for further commo
n problems.

Installation failed, reverting ./composer.json to its original content.

**Comment by jadb** [comment]
Thanks for reporting this. I forgot to tag a new release after updating composer so the 'stable' release wasn't so stable after all.

Everything should be fixed now and composer should stop complaining. Try again! :smile:
